import 'package:flutter/material.dart';
import 'package:pobe_new/features/home/widgets/app_header.dart';

class TermPage extends StatelessWidget {
  const TermPage({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            children: [
              PageHeader(title: 'Terms & Conditions'),
              SizedBox(
                width: double.infinity,
                child: Padding(
                  padding: EdgeInsets.symmetric(horizontal: 32),
                  child: Column(
                    children: [
                      SizedBox(
                        height: 20,
                      ),
                      Text(
                        'Terms And Condition Of PoBe',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 18,
                          fontWeight: FontWeight.w800,
                        ),
                      ),
                      SizedBox(
                        height: 10,
                      ),
                      Text(
                        'Last Updated:  25 April 2024',
                        style: TextStyle(
                          color: Color.fromRGBO(31, 54, 113, 0.5),
                          fontSize: 14,
                          fontWeight: FontWeight.w400,
                        ),
                      ),
                      SizedBox(
                        height: 20,
                      ),
                      Text(
                        'Terms and Conditions ("Terms") Our Terms and Conditions were last updated on [DATE]. Please read these terms and conditions carefully before using Our Service. Interpretation and Definitions Interpretation The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural. Definitions For the purposes of these Terms and Conditions: ● “Affiliate” means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority. ● “Account” means a unique account created for You to access our Service or parts of our Service. ● “Company” (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to [COMPANY_INFORMATION]. ● “Country” refers to [COMPANY_COUNTRY]. ● “Content” refers to content such as text, images, or other information that can be posted, uploaded, linked to or otherwise made available by You, regardless of the form of that content. ● “Device” means any device that can access the Service such as a computer, a cellphone or a digital tablet. ● “Feedback” means feedback, innovations or suggestions sent by You regarding the attributes, performance or features of our Service. ● “Products” refer to the products or items offered for sale on the Service. ● “Orders” mean a request by You to purchase Products from Us. ● “Promotions” refer to contests, sweepstakes or other promotions offered through the Service. ● “Service” refers to the Website. ● “Terms and Conditions” (also referred as "Terms") mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service. This Terms and Conditions Agreement was generated by TermsFeed Terms and Conditions Generator. ● “Third-party Social Media Service” means any services or content (including data, information, products or services) provided by a third-party that may be displayed, included or made available by the Service. ● “Website” refers to [WEBSITE_NAME], accessible from [WEBSITE_URL] ● “You” means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual',
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 16,
                          fontWeight: FontWeight.w400,
                        ),
                        textAlign: TextAlign.justify,
                      ),
                      SizedBox(
                        height: 50,
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
